#ifndef __WIFI_PROV_CONF__
#define __WIFI_PROV_CONF__

#define CONFIG_WIFI_SAMPLE_AP_SSID "ESP32-AP"
#define CONFIG_WIFI_SAMPLE_AP_PSK ""
#define CONFIG_WIFI_SAMPLE_SSID "SSID"
#define CONFIG_WIFI_SAMPLE_PSK "PASSWORD"
#define CONFIG_WIFI_SAMPLE_DHCPV4_START 1
#define CONFIG_WIFI_SAMPLE_AP_IP_ADDRESS "192.168.4.1"
#define CONFIG_WIFI_SAMPLE_AP_NETMASK "255.255.255.0"

#endif //  __WIFI_PROV_CONF__
